version: "3.7"

services:

  # Imagem Aplicação
  app:
    build:
      context: ./docker/php/
      dockerfile: Dockerfile
    image: app-php-apache-81
    container_name: app-gerador-de-sistemas-base
    restart: unless-stopped
    ports:
      - "9003:80"
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - network-project


 # Imagem Mysql Versão 8.0
  db:
    image: mysql:8.0
    container_name: mysql-gerador-de-sistemas-base
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3303:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./docker/mysql:/var/lib/mysql
    networks:
      - network-project

# Network Project
networks:
  network-project:
    driver: bridge